### ISSUE TITLE
Sortieren

### ISSUE THREAD

**Issue by LuisDoc** [Nilusche/Tik-Tasks#11]
Auf der Startseite:
Sortieren funktioniert nicht mehr.
Die Aufgabenliste verändert sich gar nicht

In den Gruppen:
Sortieren funktioniert prinzipiell,
es werden aber weitere Aufgaben angezeigt die nicht in der Gruppe sein sollten.
Siehe Screenshots
![image](https://user-images.githubusercontent.com/81914129/142201738-a3b369e7-69fc-4616-a72e-3e1a6824643d.png)
![image](https://user-images.githubusercontent.com/81914129/142201784-fa0500de-5372-4a1b-acce-336664a9e0b9.png)

Dabei wird auch die Edit & Sort Leiste mehrmals mitkopiert

**Comment by LuisDoc** [comment]
Wenn Sortiert wird, werden Aufgaben angezeigt, die nicht zugänglich sein sollten
Also auch Aufgaben anderer Rollen und Benutzer

**Comment by LuisDoc** [comment]
Bereits gefixed und gepushed:
[Erstellen / Sortieren / Filtern]-Leiste kommt nur noch einmalig vor

**Comment by Nilusche** [comment]
Ein Feini

**Comment by Nilusche** [comment]
Problem gelöst.
Es fehlten nur paar Variablen mit den Routen
