### ISSUE TITLE
Duplikate Startseite

### ISSUE THREAD

**Issue by LuisDoc** [Nilusche/Tik-Tasks#14]
Reproduktio:
Manager erstellt eine Aufgabe "A1" und eine Aufgabe "A2"
Manager erstellt eine "Testgruppe"und fügt "A1" in die "TestGruppe" hinzu
Manager übergibt Aufgaben an "admin@gmail.com"
Admin bekommt Aufgaben "a1" und "a2" doppelt angezeigt
![image](https://user-images.githubusercontent.com/81914129/142633966-45e0f80d-5303-480c-9872-f77a26568039.png)

**Comment by LuisDoc** [comment]
Fehler entsteht wahrscheinlich durch doppeltes bestätigen während ladezeit --> entprellen ?

**Comment by Nilusche** [comment]
Button entprellt
